//
//  Levels.swift
//  stonedge
//
//  Created by Pascal Bourguignon on 15/03/2024.
//

import Foundation

let levels = [
            """
            Level 36
            
            ...............
            ...............
            ......AO.......
            ....OOOIIO.....
            ..SOOOICOO1OT..
            ...IIOIOOO.....
            ......IO.......
            ...............
            ...............
            
            A RED 1
            1 PATHWAY CLOSED
            """,
           """
           Level 37
           
           ...........
           ...........
           .....OC....
           ....CII....
           ..OO1BS23..
           ..OR4TCOO..
           ....COL....
           .....O5....
           ...........
           ...........
           
           B BLUE 1
           R RED 4
           L RED 2 3 5
           1 PATHWAY CLOSED
           2 PATHWAY CLOSED
           3 PATHWAY CLOSED
           4 PATHWAY OPEN
           5 PATHWAY OPEN
           """,
           """
           Level 38
           
           .................
           .................
           ..II.IIIICIIOIT..
           ..II..III.IIIII..
           ..SOII.II.IIIII..
           ..IIICOOC........
           .................
           .................
           """,
           """
           Level 39
           
           ..............
           ..............
           ..IIB1R2CLO...
           ..IIO.....O...
           ....O.....O...
           ....O.....3O..
           ....O.....OO..
           ....IO...OTO..
           ....SO...CO...
           .....OCOCOO...
           ..............
           ..............
           
           B BLUE 1
           R RED 2
           L RED 3
           1 PATHWAY CLOSED
           2 PATHWAY CLOSED
           3 PATHWAY CLOSED
           """,
            
           """
           Level 52
           
           .........
           ...RO....
           ...OC....
           ..SBOC1..
           ..OTIO2..
           ..3OCO...
           ..OC.....
           
           R RED 3
           B BLUE 1 2
           1 PATHWAY CLOSED
           2 PATHWAY CLOSED
           3 PATHWAY CLOSED
           """]
